version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=llama-3.1-8b-instant
      - DATABASE_PATH=/data/data.db
    volumes:
      - ./data:/data
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001
